import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MobileNav from "@/components/shared/MobileNav";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`scroll-smooth  ${inter.className}`}>
        <div className=" max-w-4xl mx-auto scroll-smooth">{children}</div>
        <Footer></Footer>
        <Navbar></Navbar>
      </body>
    </html>
  );
}
